/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'blob' : ExternalBlob,
  'kind' : MediaKind,
  'caption' : [] | [string],
}
export interface ChatMessage {
  'id' : bigint,
  'displayName' : DisplayName,
  'text' : [] | [string],
  'sender' : Principal,
  'timestamp' : Time,
  'attachment' : [] | [Attachment],
}
export type DisplayName = string;
export type ExternalBlob = Uint8Array;
export interface MediaItem {
  'id' : bigint,
  'title' : string,
  'metadata' : [] | [string],
  'mediaType' : MediaType,
}
export type MediaKind = { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null };
export type MediaType = { 'uploadedFile' : ExternalBlob } |
  { 'externalUrl' : string };
export interface PlaybackState {
  'lastUpdate' : Time,
  'isPlaying' : boolean,
  'position' : Seconds,
  'currentMediaId' : bigint,
}
export interface Reaction {
  'displayName' : DisplayName,
  'sender' : Principal,
  'emoji' : string,
  'timestamp' : Time,
}
export type Seconds = bigint;
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'displayName' : DisplayName,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaItem' : ActorMethod<[string, MediaType, [] | [string]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearReactions' : ActorMethod<[], undefined>,
  'deleteMediaItem' : ActorMethod<[bigint], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'getAllMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllReactions' : ActorMethod<[], Array<Reaction>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHandRaises' : ActorMethod<[], Array<[Principal, boolean]>>,
  'getMediaItem' : ActorMethod<[bigint], MediaItem>,
  'getMutedChatUsers' : ActorMethod<[], Array<Principal>>,
  'getMutedReactionUsers' : ActorMethod<[], Array<Principal>>,
  'getPlaybackState' : ActorMethod<[], PlaybackState>,
  'getReactionCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lowerHand' : ActorMethod<[Principal], undefined>,
  'muteUserFromChat' : ActorMethod<[Principal], undefined>,
  'muteUserFromReactions' : ActorMethod<[Principal], undefined>,
  'registerUser' : ActorMethod<[DisplayName], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMediaMessage' : ActorMethod<
    [string, [] | [string], ExternalBlob, MediaKind],
    bigint
  >,
  'sendMessage' : ActorMethod<[DisplayName, string], bigint>,
  'sendReaction' : ActorMethod<[string, DisplayName], undefined>,
  'toggleHandRaise' : ActorMethod<[DisplayName], undefined>,
  'unmuteUserFromChat' : ActorMethod<[Principal], undefined>,
  'unmuteUserFromReactions' : ActorMethod<[Principal], undefined>,
  'updatePlaybackState' : ActorMethod<[bigint, Seconds, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];