/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'uploadedFile' : ExternalBlob,
  'externalUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'metadata' : IDL.Opt(IDL.Text),
  'mediaType' : MediaType,
});
export const DisplayName = IDL.Text;
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'displayName' : DisplayName,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : DisplayName,
});
export const Seconds = IDL.Nat;
export const PlaybackState = IDL.Record({
  'lastUpdate' : Time,
  'isPlaying' : IDL.Bool,
  'position' : Seconds,
  'currentMediaId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMediaItem' : IDL.Func(
      [IDL.Text, MediaType, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMediaItem' : IDL.Func([IDL.Nat], [MediaItem], ['query']),
  'getPlaybackState' : IDL.Func([], [PlaybackState], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([DisplayName], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([DisplayName, IDL.Text], [IDL.Nat], []),
  'updatePlaybackState' : IDL.Func([IDL.Nat, Seconds, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({
    'uploadedFile' : ExternalBlob,
    'externalUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'metadata' : IDL.Opt(IDL.Text),
    'mediaType' : MediaType,
  });
  const DisplayName = IDL.Text;
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'displayName' : DisplayName,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : DisplayName,
  });
  const Seconds = IDL.Nat;
  const PlaybackState = IDL.Record({
    'lastUpdate' : Time,
    'isPlaying' : IDL.Bool,
    'position' : Seconds,
    'currentMediaId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMediaItem' : IDL.Func(
        [IDL.Text, MediaType, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMediaItem' : IDL.Func([IDL.Nat], [MediaItem], ['query']),
    'getPlaybackState' : IDL.Func([], [PlaybackState], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([DisplayName], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([DisplayName, IDL.Text], [IDL.Nat], []),
    'updatePlaybackState' : IDL.Func([IDL.Nat, Seconds, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };